import React from 'react'
import { Table, Menu, Dropdown, Button } from 'antd'
import Column from 'antd/lib/table/Column'
import ColumnGroup from 'antd/lib/table/ColumnGroup'

const data = [
  {
    key: '1',
    userName: 'Bob',
    correct: 32,
    unCorrect: 28,
    lv1: [
      'qwertyyyyyyy',
      'qwewdwdyy',
      'qwwyyyyy',
      'qwerwdqwdyyy',
      'qwyyy',
      'qwwwdyyyyyyy',
      'qwyyy',
      'qwwdwdwdwdw',
      'qwertyy',
      'qwewfefyy',
    ],
    lv2: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv3: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv4: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv5: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv6: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    dateOfGame: new Date().toLocaleString(),
  },
  {
    key: '2',
    userName: 'Bob2',
    correct: 32,
    unCorrect: 28,
    lv1: [
      'qwertyyyyyyy',
      'qwewdwdyy',
      'qwwyyyyy',
      'qwerwdqwdyyy',
      'qwyyy',
      'qwwwdyyyyyyy',
      'qwyyy',
      'qwwdwdwdwdw',
      'qwertyy',
      'qwewfefyy',
    ],
    lv2: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv3: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv4: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv5: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv6: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    dateOfGame: new Date().toLocaleString(),
  },
  {
    key: '2',
    userName: 'Bob2',
    correct: 32,
    unCorrect: 28,
    lv1: [
      'qwertyyyyyyy',
      'qwewdwdyy',
      'qwwyyyyy',
      'qwerwdqwdyyy',
      'qwyyy',
      'qwwwdyyyyyyy',
      'qwyyy',
      'qwwdwdwdwdw',
      'qwertyy',
      'qwewfefyy',
    ],
    lv2: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv3: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv4: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv5: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv6: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    dateOfGame: new Date().toLocaleString(),
  },
  {
    key: '2',
    userName: 'Bob2',
    correct: 32,
    unCorrect: 28,
    lv1: [
      'qwertyyyyyyy',
      'qwewdwdyy',
      'qwwyyyyy',
      'qwerwdqwdyyy',
      'qwyyy',
      'qwwwdyyyyyyy',
      'qwyyy',
      'qwwdwdwdwdw',
      'qwertyy',
      'qwewfefyy',
    ],
    lv2: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv3: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv4: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv5: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv6: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    dateOfGame: new Date().toLocaleString(),
  },
  {
    key: '2',
    userName: 'Bob2',
    correct: 32,
    unCorrect: 28,
    lv1: [
      'qwertyyyyyyy',
      'qwewdwdyy',
      'qwwyyyyy',
      'qwerwdqwdyyy',
      'qwyyy',
      'qwwwdyyyyyyy',
      'qwyyy',
      'qwwdwdwdwdw',
      'qwertyy',
      'qwewfefyy',
    ],
    lv2: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv3: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv4: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv5: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv6: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    dateOfGame: new Date().toLocaleString(),
  },
  {
    key: '2',
    userName: 'Bob2',
    correct: 32,
    unCorrect: 28,
    lv1: [
      'qwertyyyyyyy',
      'qwewdwdyy',
      'qwwyyyyy',
      'qwerwdqwdyyy',
      'qwyyy',
      'qwwwdyyyyyyy',
      'qwyyy',
      'qwwdwdwdwyy',
      'qwertyy',
      'qwewfefyy',
    ],
    lv2: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv3: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv4: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv5: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv6: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    dateOfGame: new Date().toLocaleString(),
  },
  {
    key: '2',
    userName: 'Bob2',
    correct: 32,
    unCorrect: 28,
    lv1: [
      'qwertyyyyyyy',
      'qwewdwdyy',
      'qwwyyyyy',
      'qwerwdqwdyyy',
      'qwyyy',
      'qwwwdyyyyyyy',
      'qwyyy',
      'qwwdwdwdwdw',
      'qwertyy',
      'qwewfefyy',
    ],
    lv2: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv3: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv4: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv5: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    lv6: [
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
      'qwertyyyyyyy',
    ],
    dateOfGame: new Date().toLocaleString(),
  },
]

const StatisticTable = () => {
  const render = (tags: any) => (
    <Dropdown
      overlay={
        <Menu>
          {tags.map((tag: any) => (
            <Menu.Item key={tag}>{tag}</Menu.Item>
          ))}
        </Menu>
      }
      placement="bottomCenter"
      arrow
    >
      <Button>show words</Button>
    </Dropdown>
  )

  return (
    <Table bordered dataSource={data}>
      <Column title="User name" dataIndex="userName" key="userName" />
      <Column title="Correct" dataIndex="correct" key="correct" />
      <Column title="Uncorrect" dataIndex="unCorrect" key="unCorrect" />
      <ColumnGroup title="Words">
        <Column title="level 1" dataIndex="lv1" key="lv1" render={render} />
        <Column title="level 2" dataIndex="lv2" key="lv2" render={render} />
        <Column title="level 3" dataIndex="lv3" key="lv3" render={render} />
        <Column title="level 4" dataIndex="lv4" key="lv4" render={render} />
        <Column title="level 5" dataIndex="lv5" key="lv5" render={render} />
        <Column title="level 6" dataIndex="lv6" key="lv6" render={render} />
      </ColumnGroup>
      <Column title="date of game" dataIndex="dateOfGame" key="dateOfGame" />
    </Table>
  )
}

export default StatisticTable
